# Version de Kustomize
apiVersion: kustomize.config.k8s.io/v1beta1

# Type de configuration
kind: Kustomization

# Namespace appliqué automatiquement
namespace: techshop

# Liste complète des ressources Kubernetes
resources:
  - namespace.yaml
  # Secrets et ConfigMaps
  - postgres-secret.yaml
  - app-secrets.yaml
  - app-configmap.yaml
  - api-gateway-configmap.yaml
  # Stockage
  - postgres-pvc.yaml
  # Déploiements
  - postgres-deployment.yaml
  - user-deployment.yaml
  - product-deployment.yaml
  - order-deployment.yaml
  - api-gateway-deployment.yaml
  - frontend-deployment.yaml
  # Services
  - postgres-service.yaml
  - user-service.yaml
  - product-service.yaml
  - order-service.yaml
  - api-gateway-service.yaml
  - frontend-service.yaml